//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
//find the sum of the even-valued terms.

var fib = function(n) {
	var lon = [1, 2];
	for (i = lon.length; i < n; i++) {
		lon[i] = lon[i - 2] + lon[i - 1];
	};
	return lon;
};

var listOfEvenFib = function(n) {
	var loe = [];
	var lofn = fib(n);
	for (i = 0; i < n; i++) {
		if (lofn[i] % 2 === 0) {
			loe.push(lofn[i]);
		}
	};
	return loe;
};

var sumEvenFib = function(n) {	
	var sumEven = 0;
	var loe = listOfEvenFib(n);
	for (i = loe.length; i--;) {
		sumEven += loe[i];
	};
	return sumEven;
};